### ISSUE TITLE
Install from Github: Missing file theochrone/theoXML/fr_roman_martyrology.xml

### ISSUE THREAD

**Issue by BenoitEirik** [paucazou/theochrone#26]
```
~/theochrone$ python3 -c "import dataswitcher; dataswitcher.xml_to_pkl('en_roman_martyrology');dataswitcher.xml_to_pkl('fr_roman_martyrology')"
adjutoria.py :: <module> :: 25 :: WARNING :: /data/images.pkl not found. Please run dataswitcher
dataswitcher.py :: <module> :: 259 :: WARNING :: 
    Hello ! I'm the logger. I'm pretty useless,
    but I love to print weird things on the screen.
    If you can read that, that means that the module
    is completely loaded, which is a good thing.
    If you want to silent me, please just type :
    dataswitcher.logger.disabled = True
    Happy pickling !
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/sergent/theochrone/dataswitcher.py", line 232, in xml_to_pkl
    with enc.Preferences(path + 'theoXML/' + name + '.xml','r') as f:
  File "/home/sergent/theochrone/enc.py", line 317, in __init__
    io.FileIO.__init__(self, *args, **kwds)
FileNotFoundError: [Errno 2] No such file or directory: '/home/sergent/theochrone/theoXML/fr_roman_martyrology.xml'
```

**Comment by BenoitEirik** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Install from Github](https://trello.com/c/rsOjWCGO/3-install-from-github)

**Comment by paucazou** [comment]
Can you give the output of
`ls /home/sergent/theochrone/theoXML/`

?

**Comment by paucazou** [comment]
OK, just a typo in the command. Please run:
python3 -c "import dataswitcher; `dataswitcher.xml_to_pkl('en_roman_martyrology');dataswitcher.xml_to_pkl('fr_roman_martyrology_1962')"`

**Comment by paucazou** [comment]
I'll update the README.

**Comment by BenoitEirik** [comment]
> Can you give the output of
> `ls /home/sergent/theochrone/theoXML/`
> 
> ?

```
~/theochrone/theoXML$ ls /home/sergent/theochrone/theoXML/
american_1962_.xml             roman_1962_cycledenoel.xml
australian_1962_.xml           roman_1962_cycledepaques.xml
brazilian_1962_.xml            roman_1962_deuxiemetrimestre_sanctoral.xml
canadian_1962_.xml             roman_1962_dimanches.xml
english_1962_.xml              roman_1962_fetesduseigneur.xml
en_roman_martyrology.xml       roman_1962_premiertrimestre_sanctoral.xml
french_1962_.xml               roman_1962_proaliquibuslocis.xml
fr_roman_martyrology_1962.xml  roman_1962_quatriemetrimestre_sanctoral.xml
fr_word_frequency.xml          roman_1962_samedi_ferie.xml
images.xml                     roman_1962_troisiemetrimestre_sanctoral.xml
la_roman_martyrology_1749.xml  scottish_1962_.xml
la_roman_martyrology_1962.xml  spanish_1962_.xml
newzealander_1962_.xml         strasburger_1962_.xml
polish_1962_.xml               welsh_1962_.xml
portuguese_1962_.xml
```
Thank you.
